# Generated by Django 6.0.4 on 2026-04-21 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Surogātpasts / atkārtots sludinājums'), ('fraud', 'Krāpniecība / viltojums'), ('wrong_category', 'Nepareiza kategorija'), ('inappropriate', 'Nepiemērots saturs'), ('illegal', 'Nelikumīgs saturs'), ('other', 'Cits iemesls')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Jauns'), ('reviewed', 'Izskatīts'), ('resolved', 'Atrisināts')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.listing')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
