# Generated by Django 6.0.4 on 2026-04-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
