# Generated by Django 6.0.4 on 2026-04-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(choices=[('comfort', 'Komforts'), ('safety', 'Drošība'), ('media', 'Mediji un navigācija'), ('tech', 'Tehnika'), ('extra', 'Papildus')], max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['group', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='listings', to='listings.equipment'),
        ),
    ]
