# Generated by Django 6.0.4 on 2026-04-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listingimage_options_listingimage_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='moderation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Apstiprināts'), ('pending', 'Gaida apstiprināšanu'), ('rejected', 'Noraidīts')], default='approved', max_length=10),
        ),
    ]
