# Generated by Django 6.0.4 on 2026-04-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_moderation_note_listing_moderation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
