# Generated by Django 6.0.4 on 2026-04-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
