# Generated by Django 6.0.4 on 2026-04-23 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(choices=[('petrol', 'Benzīns'), ('diesel', 'Dīzelis'), ('electric', 'Elektro'), ('hybrid', 'Hibrīds'), ('gas', 'Gāze'), ('other', 'Cits')], max_length=10)),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=4)),
                ('transmission', models.CharField(choices=[('manual', 'Manuālā'), ('automatic', 'Automātiskā'), ('robot', 'Robots / Pus-automāts'), ('cvt', 'Variators (CVT)')], max_length=10)),
                ('body_type', models.CharField(choices=[('sedan', 'Sedans'), ('hatchback', 'Hečbeks'), ('wagon', 'Universāls'), ('suv', 'SUV / Apvidus'), ('coupe', 'Kupeja'), ('convertible', 'Kabriolets'), ('minivan', 'Minivens'), ('pickup', 'Pikaps'), ('van', 'Furgons'), ('other', 'Cits')], max_length=12)),
                ('has_inspection', models.BooleanField(default=True)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('reg_number', models.CharField(max_length=15, verbose_name='Reģ. numurs')),
                ('vin', models.CharField(max_length=17, verbose_name='VIN kods')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_details', to='listings.listing')),
            ],
        ),
    ]
