# Generated by Django 6.0.4 on 2026-04-24 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_autodetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TireDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.PositiveSmallIntegerField(verbose_name='Rādiuss (collas)')),
                ('width', models.PositiveSmallIntegerField(verbose_name='Platums (mm)')),
                ('profile', models.PositiveSmallIntegerField(verbose_name='Profils (%)')),
                ('season', models.CharField(choices=[('summer', 'Vasaras'), ('winter', 'Ziemas'), ('allseason', 'Vissezonas'), ('studded', 'Ziemas ar nagliņām')], max_length=10, verbose_name='Sezona')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Ražotājs')),
                ('load_index', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Slodzes indekss')),
                ('speed_index', models.CharField(blank=True, max_length=3, verbose_name='Ātruma indekss')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tire_details', to='listings.listing')),
            ],
        ),
    ]
