# Generated by Django 6.0.4 on 2026-04-24 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_tiredetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_type', models.CharField(choices=[('sell', 'Pārdod'), ('buy', 'Pērk'), ('trade', 'Maina'), ('rent', 'Izīrē'), ('lease', 'Īrē')], max_length=5, verbose_name='Darījuma veids')),
                ('country', models.CharField(max_length=100, verbose_name='Valsts')),
                ('district', models.CharField(max_length=100, verbose_name='Rajons')),
                ('city', models.CharField(max_length=100, verbose_name='Pilsēta')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='re_details', to='listings.listing')),
            ],
        ),
    ]
