# Generated by Django 6.0.4 on 2026-04-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_realestatedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pilsēta'),
        ),
        migrations.AddField(
            model_name='listing',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Valsts'),
        ),
    ]
