# Generated by Django 6.0.4 on 2026-04-24 23:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_listing_city_listing_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_fee_enabled', models.BooleanField(default=False, verbose_name='Maksa par sludinājumu ieslēgta')),
                ('listing_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Sludinājuma maksa (€ ar PVN)')),
                ('auction_fee_enabled', models.BooleanField(default=False, verbose_name='Maksa par izsoli ieslēgta')),
                ('auction_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Izsoles maksa (€ ar PVN)')),
            ],
            options={
                'verbose_name': 'Vietnes iestatījumi',
                'verbose_name_plural': 'Vietnes iestatījumi',
            },
        ),
    ]
