# Generated by Django 6.0.4 on 2026-04-24 23:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='featured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='TOP sludinājums'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_auction_enabled',
            field=models.BooleanField(default=False, verbose_name='TOP izsole ieslēgta'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_auction_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='TOP izsoles maksa (€ ar PVN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_listing_enabled',
            field=models.BooleanField(default=False, verbose_name='TOP sludinājums ieslēgts'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_listing_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='TOP sludinājuma maksa (€ ar PVN)'),
        ),
    ]
