# Generated by Django 6.0.4 on 2026-04-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_add_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodetails',
            name='mileage',
            field=models.PositiveIntegerField(default=0, verbose_name='Nobraukums (km)'),
        ),
    ]
