# Generated by Django 6.0.4 on 2026-04-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_add_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='deal_type',
            field=models.CharField(blank=True, choices=[('sell', 'Pārdod'), ('buy', 'Pērk'), ('trade', 'Maina')], default='', max_length=5),
        ),
    ]
