# Generated by Django 6.0.4 on 2026-04-26 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_add_deal_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VinReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=17)),
                ('price_net', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_eu_vat', models.BooleanField(default=False)),
                ('eu_vat_number', models.CharField(blank=True, max_length=30)),
                ('report_data', models.JSONField(blank=True, null=True)),
                ('api_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vin_reports', to='listings.listing')),
                ('purchased_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vin_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
