# Generated by Django 6.0.4 on 2026-04-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_vinreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Kods')),
                ('discount_type', models.CharField(choices=[('percent', 'Procenti (%)'), ('fixed', 'Fiksēta summa (€)')], default='percent', max_length=10, verbose_name='Atlaides veids')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Atlaides vērtība')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maks. izmantošanu reizes (tukšs = neierobežots)')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Izmantots reizes')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Derīgs no')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Derīgs līdz')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktīvs')),
            ],
            options={
                'verbose_name': 'Atlaižu kods',
                'verbose_name_plural': 'Atlaižu kodi',
                'ordering': ['-id'],
            },
        ),
    ]
