# Generated by Django 6.0.4 on 2026-04-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
