# Generated by Django 6.0.4 on 2026-05-10 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_saved_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('internal', 'Eizsole.lv'), ('direct', 'Tiešā'), ('other', 'Cits')], default='direct', max_length=10)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='listings.listing')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
    ]
