# Generated by Django 6.0.4 on 2026-05-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_listing_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='age_range',
            field=models.CharField(blank=True, choices=[('18-30', '18–30 gadi'), ('30-45', '30–45 gadi'), ('45-60', '45–60 gadi'), ('60+', 'No 60 gadiem')], max_length=10),
        ),
    ]
