# Generated by Django 6.0.4 on 2026-05-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_listing_buyer_listing_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='deal_type',
            field=models.CharField(blank=True, choices=[('sell', 'Pārdod'), ('buy', 'Pērk'), ('trade', 'Maina'), ('give', 'Atdod')], default='', max_length=5),
        ),
    ]
