# Generated by Django 6.0.4 on 2026-05-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0032_add_give_deal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='deal_type',
            field=models.CharField(blank=True, choices=[('sell', 'Pārdod'), ('buy', 'Pērk'), ('trade', 'Maina'), ('give', 'Atdod'), ('offer', 'Piedāvā')], default='', max_length=5),
        ),
    ]
