# Generated by Django 6.0.4 on 2026-06-04 02:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_sidebar_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cent_auction_commission_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='Komisija (%)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cent_auction_enabled',
            field=models.BooleanField(default=False, verbose_name='Centu izsoles ieslēgtas'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cent_auction_min_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=8, verbose_name='Min. maka atlikums dalībai (€)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cent_auction_min_bid_increment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=8, verbose_name='Min. solīšanas solis (€)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cent_auction_vat_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='PVN (%)'),
        ),
    ]
