# Generated by Django 6.0.4 on 2026-06-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0035_cent_auction_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_text_de',
            field=models.CharField(blank=True, default='Kostenlose Auktions- und Kleinanzeigenplattform', max_length=200, verbose_name='Hero teksts (DE)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_text_en',
            field=models.CharField(blank=True, default='Free auctions and classifieds platform', max_length=200, verbose_name='Hero teksts (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_text_lv',
            field=models.CharField(blank=True, default='Bezmaksas izsoļu un sludinājumu platforma', max_length=200, verbose_name='Hero teksts (LV)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_text_ru',
            field=models.CharField(blank=True, default='Бесплатная платформа аукционов и объявлений', max_length=200, verbose_name='Hero teksts (RU)'),
        ),
    ]
