# Generated by Django 6.0.4 on 2026-06-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0036_hero_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Adrese'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_company',
            field=models.CharField(blank=True, default='SIA Olaintrans', max_length=200, verbose_name='Uzņēmuma nosaukums'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='info@eizsole.lv', max_length=254, verbose_name='E-pasts'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_facebook',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_instagram',
            field=models.URLField(blank=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Tālrunis'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_reg_nr',
            field=models.CharField(blank=True, default='LV40203230849', max_length=50, verbose_name='Reģistrācijas Nr.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_twitter',
            field=models.URLField(blank=True, verbose_name='X / Twitter URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp numurs (tikai cipari)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_text_de',
            field=models.CharField(blank=True, default='Gratis Auktionen und Kleinanzeigen', max_length=200, verbose_name='Hero teksts (DE)'),
        ),
    ]
