# Generated by Django 6.0.4 on 2026-06-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0037_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='reference_url',
            field=models.URLField(blank=True, help_text='Saite uz preci ražotāja vai citas lapas katalogā (nav obligāta)', verbose_name='Atsauces saite'),
        ),
    ]
