# Generated by Django 6.0.4 on 2026-06-07 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0038_reference_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropshippingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Piegādātāja nosaukums')),
                ('supplier_url', models.URLField(blank=True, verbose_name='Saite uz preci piegādātājā')),
                ('supplier_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Piegādātāja cena (€)')),
                ('supplier_contact', models.CharField(blank=True, max_length=300, verbose_name='Piegādātāja kontakts (e-pasts/tel.)')),
                ('order_status', models.CharField(choices=[('pending', 'Gaida pasūtīšanu'), ('ordered', 'Pasūtīts no piegādātāja'), ('shipped', 'Nosūtīts pircējam'), ('delivered', 'Piegādāts'), ('cancelled', 'Atcelts')], default='pending', max_length=20, verbose_name='Pasūtījuma statuss')),
                ('supplier_order_id', models.CharField(blank=True, max_length=200, verbose_name='Piegādātāja pasūtījuma Nr.')),
                ('buyer_address', models.TextField(blank=True, verbose_name='Pircēja piegādes adrese')),
                ('notes', models.TextField(blank=True, verbose_name='Iekšējās piezīmes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktīvs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dropshipping', to='listings.listing', verbose_name='Sludinājums')),
            ],
            options={
                'verbose_name': 'Dropshipping prece',
                'verbose_name_plural': 'Dropshipping preces',
            },
        ),
    ]
