# Generated by Django 6.0.4 on 2026-06-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0039_dropshipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropshippingSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Piegādātāja nosaukums')),
                ('xml_feed_url', models.URLField(blank=True, verbose_name='XML feed URL')),
                ('api_url', models.URLField(blank=True, verbose_name='API URL')),
                ('api_key', models.CharField(blank=True, max_length=300, verbose_name='API atslēga / tokens')),
                ('notes', models.TextField(blank=True, verbose_name='Piezīmes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktīvs')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Pēdējā sinhronizācija')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dropshipping piegādātājs',
                'verbose_name_plural': 'Dropshipping piegādātāji',
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dropshipping_api_key',
            field=models.CharField(blank=True, help_text='Ja tukšs — bezmaksas piekļuve feed. Ģenerē random virkni drošībai.', max_length=64, verbose_name='Dropshipping API atslēga'),
        ),
    ]
