# Generated by Django 6.0.4 on 2026-06-07 11:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0040_dropshipping_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatterhornConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_feed_url', models.URLField(help_text='Matterhorn XML plūsmas adrese ar autorizāciju', verbose_name='XML feed URL')),
                ('api_username', models.CharField(blank=True, max_length=200, verbose_name='API lietotājvārds')),
                ('api_password', models.CharField(blank=True, max_length=200, verbose_name='API parole')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='Automātiskā sinhronizācija (ik 2h)')),
                ('markup_percent', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Procentuāls uzcenojums virs vairumcenas', max_digits=5, verbose_name='Uzcenojums (%)')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Pēdējā sinhronizācija')),
                ('sync_log', models.TextField(blank=True, verbose_name='Sinhronizācijas žurnāls')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.category', verbose_name='Noklusējuma kategorija')),
            ],
            options={
                'verbose_name': 'Matterhorn konfigurācija',
                'verbose_name_plural': 'Matterhorn konfigurācija',
            },
        ),
        migrations.CreateModel(
            name='MatterhornProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matterhorn_id', models.CharField(max_length=100, unique=True, verbose_name='Matterhorn ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nosaukums')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Zīmols')),
                ('description', models.TextField(blank=True, verbose_name='Apraksts')),
                ('category_path', models.CharField(blank=True, max_length=500, verbose_name='Kategorija (no Matterhorn)')),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Vairumcena (EUR)')),
                ('retail_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Pārdošanas cena (EUR)')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Valūta')),
                ('image_urls', models.JSONField(default=list, verbose_name='Attēlu URL saraksts')),
                ('sizes_stock', models.JSONField(default=dict, verbose_name='Izmēri un krājumi {izmērs: {stock, ean}}')),
                ('colors', models.JSONField(default=list, verbose_name='Krāsas')),
                ('ean_codes', models.JSONField(default=list, verbose_name='EAN kodi')),
                ('product_url', models.URLField(blank=True, verbose_name='Saite uz Matterhorn produktu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktīvs')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matterhorn_product', to='listings.listing', verbose_name='Sludinājums')),
            ],
            options={
                'verbose_name': 'Matterhorn produkts',
                'verbose_name_plural': 'Matterhorn produkti',
                'ordering': ['-created_at'],
            },
        ),
    ]
