# Generated by Django 6.0.4 on 2026-06-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0041_matterhorn'),
    ]

    operations = [
        migrations.AddField(
            model_name='matterhornconfig',
            name='api_key',
            field=models.CharField(blank=True, help_text='Matterhorn Wholesale B2B API key (token)', max_length=500, verbose_name='B2B API atslēga'),
        ),
        migrations.AlterField(
            model_name='matterhornconfig',
            name='api_password',
            field=models.CharField(blank=True, max_length=200, verbose_name='API parole (ja nepieciešams)'),
        ),
        migrations.AlterField(
            model_name='matterhornconfig',
            name='api_username',
            field=models.CharField(blank=True, max_length=200, verbose_name='API lietotājvārds (ja nepieciešams)'),
        ),
        migrations.AlterField(
            model_name='matterhornconfig',
            name='xml_feed_url',
            field=models.URLField(help_text='Matterhorn XML plūsmas adrese', verbose_name='XML feed URL'),
        ),
    ]
