# Generated by Django 6.0.4 on 2026-04-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('private', 'Privātpersona'), ('company', 'Uzņēmums')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adrese'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Uzņēmuma nosaukums'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kontaktpersona'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='legal_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Juridiskā adrese'),
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Personas kods'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reg_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Reģistrācijas numurs'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vat_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='PVN reģistrācijas numurs'),
        ),
    ]
