# Generated by Django 6.0.4 on 2026-05-14 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_emailchangerequest'),
        ('listings', '0031_listing_buyer_listing_is_sold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rating',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='listings.listing'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('reviewer', 'reviewed', 'listing')},
        ),
    ]
