# Generated by Django 6.0.4 on 2026-06-06 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_rating_unique_together_rating_listing_and_more'),
        ('auctions', '0009_cent_delivery_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='auction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating', to='auctions.auction'),
        ),
    ]
