# Generated by Django 6.0.4 on 2026-06-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('privacy', 'Privātuma politika'), ('terms', 'Lietošanas noteikumi'), ('faq', 'Jautājumi un atbildes')], max_length=20, unique=True, verbose_name='Lapas veids')),
                ('title_lv', models.CharField(max_length=200, verbose_name='Virsraksts (LV)')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Virsraksts (RU)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Virsraksts (EN)')),
                ('title_de', models.CharField(blank=True, max_length=200, verbose_name='Virsraksts (DE)')),
                ('content_lv', models.TextField(help_text='HTML atbalstīts', verbose_name='Saturs (LV)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Saturs (RU)')),
                ('content_en', models.TextField(blank=True, verbose_name='Saturs (EN)')),
                ('content_de', models.TextField(blank=True, verbose_name='Saturs (DE)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicēts')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statiska lapa',
                'verbose_name_plural': 'Statiskas lapas',
            },
        ),
    ]
