# Generated by Django 6.0.4 on 2026-04-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_is_auto_proxybid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='anti_snipe_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
