# Generated by Django 6.0.4 on 2026-06-03 22:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_anti_snipe_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_type',
            field=models.CharField(choices=[('english', 'Angļu izsole'), ('dutch', 'Holandiešu izsole')], default='english', max_length=10),
        ),
        migrations.AddField(
            model_name='auction',
            name='dutch_interval_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='dutch_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='dutch_price_step',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
