# Generated by Django 6.0.4 on 2026-06-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_dutch_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_cent_auction',
            field=models.BooleanField(default=False),
        ),
    ]
