# Generated by Django 6.0.4 on 2026-06-04 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_cent_auction_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentAuctionEscrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_to_seller', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('held', 'Nauda noturēta platformā'), ('shipped', 'Pārdevējs apstiprinājis nosūtīšanu'), ('delivered', 'Pircējs apstiprinājis saņemšanu'), ('released', 'Nauda pārskaitīta pārdevējam'), ('refunded', 'Nauda atmaksāta pircējam'), ('disputed', 'Strīds — admin izskata')], default='held', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_info', models.CharField(blank=True, max_length=300, verbose_name='Izsekošanas Nr.')),
                ('note', models.TextField(blank=True, verbose_name='Piezīme')),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='auctions.auction')),
            ],
            options={
                'verbose_name': 'Centu izsoles depozīts',
                'verbose_name_plural': 'Centu izsoles depozīti',
            },
        ),
    ]
