# Generated by Django 6.0.4 on 2026-06-04 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_cent_auction_escrow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('office', 'Administratora birojā'), ('agreed', 'Norunātā vietā'), ('courier', 'Kurjers → administrators → pircējs')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='CentAuctionRulesAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cent_auction_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Centu izsoles noteikumu piekrišana',
                'verbose_name_plural': 'Centu izsoles noteikumu piekrišanas',
            },
        ),
    ]
